// File generated by Antigravity Autonomous Firebase Setup.
// uchiwa-ia project configuration.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return web;
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5SytIcIzJ4mdlOOlFccA5fVllQZGZsu0',
    appId: '1:1017268280190:web:ee757029853bf78f0b712f',
    messagingSenderId: '1017268280190',
    projectId: 'uchiwa-ia',
    authDomain: 'uchiwa-ia.firebaseapp.com',
    storageBucket: 'uchiwa-ia.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVCqKNolTUhLzAfe0EUikQp8RsL2rtLVA',
    appId: '1:1017268280190:android:650bf9830cbf1de60b712f',
    messagingSenderId: '1017268280190',
    projectId: 'uchiwa-ia',
    storageBucket: 'uchiwa-ia.firebasestorage.app',
  );
}
